spring:
  config:
    import: secrets.yml
  application:
    name: record-management
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 9192
  servlet:
    context-path: /record

# Cloud Configuration
cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access-key}
      secret-key: ${aws.credentials.secret-key}
    region:
      static: ${aws.region.static}
    stack:
      auto: false

application:
  bucket:
    name: hospitalmgmt-record-service

# Logging Configuration
logging:
  file:
    name: record-management-service.log
    max-size: 10MB
    max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

# Sonar Configuration
sonar:
  projectKey: record-management-service
  projectName: Hospital Management project
  host:
    url: http://localhost:9000