spring:
  config:
    import: secrets.yml
  application:
    name: record-management
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

server:
  port: 9192
  servlet:
    context-path: /v1/record

cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access-key}
      secret-key: ${aws.credentials.secret-key}
    region:
      static: ${aws.region.static}
    stack:
      auto: false

application:
  bucket:
    name: hospitalmgmt-record-service
